title:              Son's Warehouse
email:              sonsh0824@gmail.com
description:        A Blog For Software Developers
author:             Seong ho
baseurl:            #"/startbootstrap-clean-blog-jekyll"
url:                "https://sonsh0824.github.io"

# Social Profiles
twitter_username:   #Bootstrap
github_username:    #
facebook_username:  #StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:          /:categories/:title
paginate:           5
paginate_path:      "/posts/page:num/"
timezone:           Asia/Seoul
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Site Footer
footer:
  links:
    -label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/sonsh0824"
